### PR TITLE
Allow prefixing the syncing toots and tweets

### LINKED ISSUE #79: Make hard-coded prefixes configurable
As of now, some prefixes are hard-coded, _e.g._, `RT` for a RT from Twitter. It would be nice if it could be configurable.

### PR DESCRIPTION
**Pull request by pan93412**
Fix #79

## Description

Allow adding a prefix to the message, which is going to forward to Mastodon-side or Twitter-side. It is useful when you want to let readers know where this message is from.

image

## Implementation

It will add prefix to *every* messages forward – it is implemented in `send_single_post_to_(side)`.

### CODE REVIEW

**Comment by klausi** [comment]
Thanks, I'm not sure yet if we should implement this new feature. It adds quite a bit of complexity to the code base.

Before we discuss implementation details of the pull request I would like to get some feedback, anyone else that needs this feature?

**Comment by nfrankel** [comment]
What I'd need is to remove the `RT` prefix from Twitter to Mastodon. It would be nice is it could be configured, _e.g._, `RT` as of now, nothing, `Twitter`, etc.

**Comment by klausi** [comment]
@nfrankel I think that would be a different feature request for retweets/reblogs compared to the proposed changes here, please open a new issue for that.

**Comment by nfrankel** [comment]
As per you request https://github.com/klausi/mastodon-twitter-sync/issues/79

**Comment by pan93412** [comment]
Added the `Fix` note in this PR description. BTW, I currently leave the PR as it is (I don't resolve conflict at this monent).

**Pull request closed without merging**
